version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo
    ports:
    - "5432:5432"
    networks:
    - database-tier
    secrets:
    - postgres_password

  api:
    image: openjdk:8-jdk-alpine
    ports:
    - "8081:8080"
    volumes:
    - .:/app
    working_dir: /app
    command: './gradlew bootRun'
    networks:
    - api-tier
    - database-tier
    secrets:
    - postgres_password
  front:
    image: node:8
    ports:
    - "8082:8080"
    volumes:
    - .:/app
    - node_modules:/app/node_modules
    working_dir: /app
    command: 'sh ./front-dev.sh'
    environment:
      - API_URL_DEV=http://localhost:8081/api/v1
    networks:
    - front-tier
    - api-tier

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password

networks:
  front-tier:
  api-tier:
  database-tier:
  payment:
    driver: overlay

volumes:
  node_modules:
    driver: 'local'