version: "3.1"

services:
  todo_db:
    image: postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo
    ports:
    - "5432:5432"
    networks:
    - back-tier
    secrets:
    - postgres_password

  todo_api:
    image: openjdk:8-jdk-alpine
    ports:
    - "8081:8080"
    volumes:
    - .:/app
    working_dir: /app
    command: './gradlew bootRun'
    networks:
    - front-tier
    - back-tier
    secrets:
    - postgres_password

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay